enable changing insert mode table mappings
vimwiki/vimwiki pull request #1048
Opened 2020-11-09 19:38 UTC by amitbeka

Mapping `<Tab>` and `<S-Tab>` at insert mode sometimes collide with
other plugins which utilize these for completions (e.g. coc example
mapping).

Since for many users the case for completion is more frequent than table
editing, this patch enables changing these mappings using the options
`g:vimwiki_tbl_next_cell` and `g:vimwiki_tbl_prev_cell`.

This patch makes it easier of those using multiple plugins and have no
desire or knowledge in debugging the collision.
It complements #1030 by providing a more direct and documented method
for setting custom keymappings.

Signed-off-by: Amit Beka <--->

Steps for submitting a pull request:

- [X] **ALL** pull requests should be made against the `dev` branch!
- [X] Take a look at [CONTRIBUTING.MD](https://github.com/vimwiki/vimwiki/blob/dev/CONTRIBUTING.md)
- [X] Reference any related issues.
- [X] Provide a description of the proposed changes.
- [X] PRs must pass Vint tests and add new Vader tests as applicable.
- [X] Make sure to update the documentation in `doc/vimwiki.txt` if applicable,
      including the Changelog and Contributors sections.

2020-11-09 21:51 UTC, tinmarino commented
Hello,

Thank you for the PR. Some changes must be made because this is a PR for "those who want to remap the <Tab> key for table navigation" and we cannot treat all those who want to remap keys specifically (even if in this case they are already lol). You can improve the table tab key magement alongside ALL the others which would make your PR much more usefull and easy to maintain

1/ Look at the way to add configuration variable in vars.vim (it is centralized => Much easier to test and maintain) (we cannot accept a PR that have a config not in this file.
2/ Look at vimwiki#u#map_key other key mapping are using
3/ Make table use it
4/ Make it configurable like remap <tab> -> >>

Otherwise, you can keep all this configuration in your vimrc and paste here the code for others to copy paste it

2020-11-09 21:52 UTC, tinmarino requested changes
See comment

2020-11-10 04:21 UTC, amitbeka commented
Sure, I can change these. I had an impression that `vimwiki#u#map_key` won't handle this, because it is currently used only for `<Plug>` commands, so I was unsure if it was by design.

What exactly do you mean by "make it configurable like remap -> >>"? Not sure I've understood.

2020-11-10 12:07 UTC, tinmarino commented
> What exactly do you mean by "make it configurable like remap -> >>"? Not
sure I've understood.

To have something like a dictionarry so that you can change mappings to
remap tab to >> so that >> is doing what tab is suposed to do.
Or to choose directly the keystoke to map to a certain function.

On Tue, Nov 10, 2020, 01:22 Amit Beka <notifications@github.com> wrote:

> Sure, I can change these. I had an impression that vimwiki#u#map_key
> won't handle this, because it is currently used only for <Plug> commands,
> so I was unsure if it was by design.
>
> What exactly do you mean by "make it configurable like remap -> >>"? Not
> sure I've understood.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/vimwiki/vimwiki/pull/1048#issuecomment-724440615>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABOXDOT5AQVZCTAT5MCBGDLSPC5WPANCNFSM4TPYUE2A>
> .
>

2020-11-10 12:10 UTC, tinmarino commented
In the function, you read the user dic and if the left side (keystroke) or
rhe right side (fubction) is in the dic, tou use the value from the dic
instead of the default.
After this is done, default can be set in this dic in vars.vim for example.
And user can change them before loading vimwiki

On Tue, Nov 10, 2020, 09:07 martin tourneboeuf <martin.tourneboeuf@gmail.com>
wrote:

> > What exactly do you mean by "make it configurable like remap -> >>"?
> Not sure I've understood.
>
> To have something like a dictionarry so that you can change mappings to
> remap tab to >> so that >> is doing what tab is suposed to do.
> Or to choose directly the keystoke to map to a certain function.
>
> On Tue, Nov 10, 2020, 01:22 Amit Beka <notifications@github.com> wrote:
>
>> Sure, I can change these. I had an impression that vimwiki#u#map_key
>> won't handle this, because it is currently used only for <Plug>
>> commands, so I was unsure if it was by design.
>>
>> What exactly do you mean by "make it configurable like remap -> >>"? Not
>> sure I've understood.
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/vimwiki/vimwiki/pull/1048#issuecomment-724440615>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ABOXDOT5AQVZCTAT5MCBGDLSPC5WPANCNFSM4TPYUE2A>
>> .
>>
>

2020-11-13 01:21 UTC, tinmarino commented
You can have a look at #1047  and `vimwiki#u#map_key`

2020-11-13 04:35 UTC, amitbeka commented
Thanks, I hope to get back to this PR today or tmrw

2020-11-15 08:50 UTC, amitbeka commented
Done fixing, would be happy for more comments

2020-11-19 12:53 UTC, tinmarino commented
@amitbeka sorry I did not notice your comment (until you request review which was a good idea).

This PR improves the code because:
1/ It is more table, easier to refactor
2/ Doc
3/ Very easy to disable the map (2 ways)
4/ Very easy to remap: Read the doc.

I would have been glad to see some test, but I'll keep a ref to it and will do it with some others.
Anyway, thank you.

2020-11-19 12:55 UTC, merged

2021-01-25 19:38 UTC, physicophilic commented
Hi.. how can I use this feature? I have the latest release, but this is a newer feature (and I would love it).

2021-01-25 20:42 UTC, tinmarino commented
@physicophilic you have to "checkout to the dev branch"
Go to the folder where your vimwiki plugin is installed and run something like `git checkout origin/dev` or ask you plugin manager to follow the dev branch and not the master one.

2021-01-26 06:29 UTC, physicophilic commented
Thank you. Setting the dev branch from the plugin manager worked. I couldn't make git commands work though; not familiar with git.